import React, { use } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import PageLayout from "./PageLayout";
import PageFooter from "./PageFooter";
import MainButton from "./MainButton";


const handleContact = () => {
  window.open("https://forms.gle/M3mHbBUp3E6sD4daA");
};

export default function TermsOfUse() {
  const navigate = useNavigate();
  const location = useLocation();

  const cameFromOnboarding = location.state?.fromOnboarding ?? false;
  
  const handleReturn = () => {
    if (cameFromOnboarding) {
      navigate("/onboarding", { state: {step: 3 } });
    } else {
      navigate(-1);
    }
  };
  return (
    <PageLayout
      showBack={false}
      footer={
        <PageFooter>
          <MainButton onClick={handleReturn} label="Return" />
        </PageFooter>
      }
    >
    <div className="bg-[#1B1F23] text-white px-4 py-8 max-w-xl mx-auto">
      <h1 className="text-2xl md:text-3xl font-bold mb-6 text-center">
        Terms of Use
      </h1>

      <p className="text-sm text-gray-400 mb-8 text-center">
        Last updated: April 7, 2025
      </p>

      <div className="space-y-6 text-base leading-relaxed text-left">
        <p>
          BetterConvo is a tool that helps users prepare for difficult conversations
          using generative AI. By using this product, you agree to the terms outlined below.
        </p>

        <div>
          <h2 className="font-semibold text-lg mb-1">1. No Private Information</h2>
          <p>
  Don’t enter personal or sensitive information.
  For your safety, BetterConvo is not designed to collect or store any personally identifiable or sensitive data.
  Please avoid including anything that could be traced back to you or someone else.
</p>

<ul className="list-disc ml-6 mt-2 space-y-1 text-base">
  <li>Full names (yours or others)</li>
  <li>Email addresses or phone numbers</li>
  <li>Social media handles or usernames</li>
  <li>Home, work, or school addresses</li>
  <li>Workplace or organization names</li>
  <li>Personal stories with identifying details</li>
  <li>Legal case details or reference numbers</li>
  <li>Medical conditions or diagnoses</li>
  <li>Financial information (bank accounts, income, etc.)</li>
  <li>Passwords or login information</li>
  <li>Government-issued IDs (driver's license, passport, etc.)</li>
  <li>Any content involving minors or vulnerable individuals</li>
</ul>

<p className="mt-4">
  Keep your input general and anonymous — for example, say “a coworker,” “a close friend,” or “a family member” instead of names or job titles.
</p>

        </div>

        <div>
          <h2 className="font-semibold text-lg mb-1">2. AI-Generated Content</h2>
          <p>
            The scripts generated by BetterConvo are produced by a generative AI system.
            These suggestions are not reviewed by professionals, and we do not guarantee their
            accuracy, safety, or emotional effectiveness.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-1">3. Intended Use</h2>
          <p>
            This tool is for educational and self-reflective use only. It is not intended
            to replace professional advice, therapy, or legal guidance.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-1">4. Data and Privacy</h2>
          <p>
            We collect anonymous usage data to improve the product. No personally
            identifiable information is stored or tracked.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-1">5. Acceptance</h2>
          <p>
            By continuing to use BetterConvo, you acknowledge that you’ve read, understood,
            and agreed to these Terms of Use.
          </p>
        </div>
      </div>

      <p className="text-center text-sm text-gray-400 mt-12">
        Have questions?{" "}
        <a 
            href="https://forms.gle/M3mHbBUp3E6sD4daA"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-400 underline hover:text-blue-300">
                Contact us
            </a>
      </p>
    </div>
    </PageLayout>
  );
}
